version: '3.1'
services:
  hello:
    image: thelittlewho/todo-service:main
    ports:
      - 8080:8080
    environment:
      ENVIRONMENT_NAME: local
      MONGODB_CONECTION_URL: mongodb://root:example@mongo:27017/
    restart: always
  mongo:
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example